package vista;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;

/**
 *
 * @author DevBuster
 */
public class RegistroAlumnos extends javax.swing.JFrame {

    // VARIABLES GLOBALES
    DefaultTableModel tablaModelo = new DefaultTableModel();
    ArrayList<Alumno> listaAlumnos = new ArrayList<>();

    /**
     * Creates new form RegistroAlumnos
     */
    public RegistroAlumnos() {
        initComponents();
        this.setTitle("GESTOR DE ALUMNOS");
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        tablaModelo.addColumn("NOMBRE");
        tablaModelo.addColumn("APELLIDO");
        tablaModelo.addColumn("EDAD");
        tablaModelo.addColumn("IDENTIFICACIÓN");
        tablaModelo.addColumn("CARRERA");
        tablaModelo.addColumn("GRUPO");
        tablaModelo.addColumn("SEMESTRE");
        tablaModelo.addColumn("PROMEDIO");

        refrescarTabla();
    }

    public final void refrescarTabla() {
        /*
        * ELIMINA LAS FILAS CADA VEZ QUE SE LLAME AL METODO PARA EVITAR DATOS
        * DUPLICADOS
         */
        while (tablaModelo.getRowCount() > 0) {
            tablaModelo.removeRow(0);
        }

        /*
        * RECORREMOS EL OBJETO Y LO ALMACENAMOS EN UN VECTOR DE 8 POSICIONES,
        * 1 POSICION POR CADA VARIABLE O CAMPO QUE TENGAMOS EN EL MODELO ALUMNO
        * NOTA: TIPO DE DATO OBJECT PARA ALMACENAR CUALQUIER TIPO DE DATO
         */
        for (Alumno listaAlumno : listaAlumnos) {
            Object objetoAlumno[] = new Object[8];
            objetoAlumno[0] = listaAlumno.getNombre();
            objetoAlumno[1] = listaAlumno.getApellido();
            objetoAlumno[2] = listaAlumno.getEdad();
            objetoAlumno[3] = listaAlumno.getIdentificacion();
            objetoAlumno[4] = listaAlumno.getCarrera();
            objetoAlumno[5] = listaAlumno.getGrupo();
            objetoAlumno[6] = listaAlumno.getSemestre();
            objetoAlumno[7] = listaAlumno.getPromedio();

            tablaModelo.addRow(objetoAlumno);
        }
        tblAlumno.setModel(tablaModelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosAlumno = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        lblIdentificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        lblCarrera = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        lblGrupo = new javax.swing.JLabel();
        cmbGrupo = new javax.swing.JComboBox<>();
        lblSemestre = new javax.swing.JLabel();
        cmbSemestre = new javax.swing.JComboBox<>();
        lblPromedio = new javax.swing.JLabel();
        spnPromedio = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEliminarTodo = new javax.swing.JButton();
        pnlTablaAlumno = new javax.swing.JPanel();
        splTablaAlumno = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlDatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Alumno"));
        pnlDatosAlumno.setToolTipText("");

        lblNombre.setText("Nombre:");

        txtNombre.setToolTipText("Nombre del Alumno");

        lblApellido.setText("Apellido:");

        txtApellido.setToolTipText("Apellido del Alumno");

        lblEdad.setText("Edad:");

        spnEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnEdad.setToolTipText("Edad del Alumno");

        lblIdentificacion.setText("Identificación:");

        txtIdentificacion.setToolTipText("Identificacion del Alumno");

        lblCarrera.setText("Carrera:");

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algoritmo", "Programacion", "Desarrollo Web", "Desarrollo Movil" }));
        cmbCarrera.setToolTipText("Carrera del Alumno");

        lblGrupo.setText("Grupo:");

        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbGrupo.setToolTipText("Grupo del Alumno");
        cmbGrupo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSemestre.setText("Semestre:");

        cmbSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbSemestre.setToolTipText("Semestre del Alumno");

        lblPromedio.setText("Promedio:");

        spnPromedio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 5.0d, 0.1d));
        spnPromedio.setToolTipText("Promedio del Alumno");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEliminarTodo.setText("Eliminar Todo");
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosAlumnoLayout = new javax.swing.GroupLayout(pnlDatosAlumno);
        pnlDatosAlumno.setLayout(pnlDatosAlumnoLayout);
        pnlDatosAlumnoLayout.setHorizontalGroup(
            pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosAlumnoLayout.createSequentialGroup()
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosAlumnoLayout.createSequentialGroup()
                        .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosAlumnoLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblApellido)
                                    .addComponent(lblNombre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosAlumnoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEdad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spnEdad)
                            .addComponent(txtNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosAlumnoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarrera, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPromedio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSemestre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGrupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCarrera, 0, 524, Short.MAX_VALUE)
                            .addComponent(cmbSemestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnPromedio)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(pnlDatosAlumnoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlDatosAlumnoLayout.setVerticalGroup(
            pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupo))
                .addGap(9, 9, 9)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar)
                    .addComponent(btnEliminarTodo))
                .addGap(21, 21, 21))
        );

        pnlTablaAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Alumnos"));

        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnoMouseClicked(evt);
            }
        });
        splTablaAlumno.setViewportView(tblAlumno);

        javax.swing.GroupLayout pnlTablaAlumnoLayout = new javax.swing.GroupLayout(pnlTablaAlumno);
        pnlTablaAlumno.setLayout(pnlTablaAlumnoLayout);
        pnlTablaAlumnoLayout.setHorizontalGroup(
            pnlTablaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splTablaAlumno)
                .addContainerGap())
        );
        pnlTablaAlumnoLayout.setVerticalGroup(
            pnlTablaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splTablaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTablaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatosAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            Alumno objetoAlumno = new Alumno();
            objetoAlumno.setNombre(txtNombre.getText());
            objetoAlumno.setApellido(txtApellido.getText());
            objetoAlumno.setEdad(Integer.parseInt(spnEdad.getValue().toString()));
            objetoAlumno.setIdentificacion(Integer.parseInt(txtIdentificacion.getText()));
            objetoAlumno.setCarrera(cmbCarrera.getSelectedItem().toString());
            objetoAlumno.setGrupo(Integer.parseInt(cmbGrupo.getSelectedItem().toString()));
            objetoAlumno.setSemestre(cmbSemestre.getSelectedItem().toString());
            objetoAlumno.setPromedio(Double.parseDouble(spnPromedio.getValue().toString()));
            listaAlumnos.add(objetoAlumno);

            refrescarTabla();
            btnBorrarActionPerformed(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR AL AGREGAR EL REGISTRO\n Tipo de error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtNombre.setText("");
        txtApellido.setText("");
        spnEdad.setValue(1);
        txtIdentificacion.setText("");
        cmbCarrera.setSelectedIndex(0);
        cmbGrupo.setSelectedIndex(0);
        cmbSemestre.setSelectedIndex(0);
        spnPromedio.setValue(0);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(this, "¿SEGURO(A) QUE QUIERE EDITAR EL REGISTRO?", "CONFIRMAR PROCESO", JOptionPane.INFORMATION_MESSAGE);

        switch (mensaje) {
            case JOptionPane.YES_OPTION -> {
                try {
                    Alumno objetoAlumno = new Alumno();
                    objetoAlumno.setNombre(txtNombre.getText());
                    objetoAlumno.setApellido(txtApellido.getText());
                    objetoAlumno.setEdad(Integer.parseInt(spnEdad.getValue().toString()));
                    objetoAlumno.setIdentificacion(Integer.parseInt(txtIdentificacion.getText()));
                    objetoAlumno.setCarrera(cmbCarrera.getSelectedItem().toString());
                    objetoAlumno.setGrupo(Integer.parseInt(cmbGrupo.getSelectedItem().toString()));
                    objetoAlumno.setSemestre(cmbSemestre.getSelectedItem().toString());
                    objetoAlumno.setPromedio(Double.parseDouble(spnPromedio.getValue().toString()));

                    int fila = tblAlumno.getSelectedRow();

                    listaAlumnos.set(fila, objetoAlumno);

                    refrescarTabla();
                    btnBorrarActionPerformed(evt);

                    JOptionPane.showMessageDialog(this, "REGISTRO EDITADO", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                } catch (HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "ERROR AL EDITAR EL REGISTRO\n Tipo de error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            case JOptionPane.NO_OPTION ->
                JOptionPane.showMessageDialog(this, "PROCESO DENEGADO", "INFORMACIÓN", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(this, "PROCESO CANCELADO", "INFORMACIÓN", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnoMouseClicked
        int seleccionarFila = tblAlumno.getSelectedRow();

        txtNombre.setText(String.valueOf(tblAlumno.getValueAt(seleccionarFila, 0)));
        txtApellido.setText(String.valueOf(tblAlumno.getValueAt(seleccionarFila, 1)));
        spnEdad.setValue(Integer.valueOf(tblAlumno.getValueAt(seleccionarFila, 2).toString()));
        txtIdentificacion.setText(String.valueOf(tblAlumno.getValueAt(seleccionarFila, 3)));
        cmbCarrera.setSelectedItem(String.valueOf(tblAlumno.getValueAt(seleccionarFila, 4)));
        cmbGrupo.setSelectedItem(String.valueOf(tblAlumno.getValueAt(seleccionarFila, 5)));
        cmbSemestre.setSelectedItem(String.valueOf(tblAlumno.getValueAt(seleccionarFila, 6)));
        spnPromedio.setValue(Double.valueOf(tblAlumno.getValueAt(seleccionarFila, 7).toString()));
    }//GEN-LAST:event_tblAlumnoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(this, "¿SEGURO(A) QUE QUIERE ELIMINAR EL REGISTRO?", "CONFIRMAR PROCESO", JOptionPane.INFORMATION_MESSAGE);

        switch (mensaje) {
            case JOptionPane.YES_OPTION -> {
                try {
                    if (tblAlumno.getSelectedRowCount() != 0) {
                        int seleccionarFila = tblAlumno.getSelectedRow();
                        tablaModelo.removeRow(seleccionarFila);

                        listaAlumnos.remove(seleccionarFila);

                        refrescarTabla();
                        btnBorrarActionPerformed(evt);

                        JOptionPane.showMessageDialog(this, "REGISTRO ELIMINADO", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para eliminar el registro", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(this, "ERROR AL ELIMINAR El REGISTRO\n Tipo de error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            case JOptionPane.NO_OPTION ->
                JOptionPane.showMessageDialog(this, "PROCESO DENEGADO", "INFORMACIÓN", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(this, "PROCESO CANCELADO", "INFORMACIÓN", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed
        int filas = tblAlumno.getRowCount();

        if (filas != 0) {
            int mensaje = JOptionPane.showConfirmDialog(this, "¿SEGURO(A) QUE QUIERE ELIMINAR TODO EL REGISTRO?", "CONFIRMAR PROCESO", JOptionPane.INFORMATION_MESSAGE);

            switch (mensaje) {
                case JOptionPane.YES_OPTION -> {
                    try {

                        for (int i = filas - 1; i >= 0; i--) {
                            tablaModelo.removeRow(i);
                            listaAlumnos.remove(i);
                        }

                        refrescarTabla();
                        btnBorrarActionPerformed(evt);

                        JOptionPane.showMessageDialog(this, "REGISTROS ELIMINADOS", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                    } catch (HeadlessException e) {
                        JOptionPane.showMessageDialog(this, "ERROR AL ELIMINAR TODOS REGISTRO\n Tipo de error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                case JOptionPane.NO_OPTION ->
                    JOptionPane.showMessageDialog(this, "PROCESO DENEGADO", "INFORMACIÓN", JOptionPane.ERROR_MESSAGE);
                default ->
                    JOptionPane.showMessageDialog(this, "PROCESO CANCELADO", "INFORMACIÓN", JOptionPane.CANCEL_OPTION);
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HAY REGISTROS POR ELIMINAR", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistroAlumnos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTodo;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbGrupo;
    private javax.swing.JComboBox<String> cmbSemestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JPanel pnlDatosAlumno;
    private javax.swing.JPanel pnlTablaAlumno;
    private javax.swing.JScrollPane splTablaAlumno;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JSpinner spnPromedio;
    private javax.swing.JTable tblAlumno;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
